version: "3.9"

services:
  db:
    image: postgres:16
    container_name: coffee_postgres
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coffee_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${PG_DB}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASSWORD}
    ports:
      - "${APP_PORT}:8080"

volumes:
  pg_data:
